import { interfazUsuario } from './usuarios';

export const USUARIOS: interfazUsuario[] = [
  { id: 1, 
    nombre: 'Adri',
    dni:"48685511-X",
    apellidos:"sanchez martinez",
    usuario:"adrijaja",
    password:"jaja1234",
    foto:"png1",
    direccion:"Calle de la Inquisición 1",
    telefono:123456789,
    tipo_usuario:"alumno",
    activo:true },

  { id: 2, 
    nombre: 'Jose',
    dni:"11685511-X",
    apellidos:"gonzález pérez",
    usuario:"JosePego",
    password:"jiji1234",
    foto:"png2",
    direccion:"Calle de la Anarquia 2",
    telefono:823456789,
    tipo_usuario:"alumno,",
    activo:true },
    
  { id: 3, 
    nombre: 'Fernando',
    dni:"88685511-X",
    apellidos:"sánchez pérez",
    usuario:"ferjustice",
    password:"jiji1234",
    foto:"png2",
    direccion:"Calle de la Justicia 3",
    telefono:825856789,
    tipo_usuario:"alumno",
    activo:true },
    
  { id: 4, 
    nombre: 'Fulgencio',
    dni:"15585511-X",
    apellidos:"morales pérez",
    usuario:"lider supremo",
    password:"jiji1234",
    foto:"png2",
    direccion:"Calle del líder supremo 2",
    telefono:753456789,
    tipo_usuario:"alumno",
    activo:true },
    
  { id: 5, 
    nombre: 'Joaquín',
    dni:"13688511-X",
    apellidos:"martínez pérez",
    usuario:"GOD",
    password:"jiji1234",
    foto:"png2",
    direccion:"Calle del SQL 21",
    telefono:243456789,
    tipo_usuario:"profesor",
    activo:true },
    
  { id: 6, 
    nombre: 'MariCris',
    dni:"74685511-X",
    apellidos:"Lidón pérez",
    usuario:"desertora 34",
    password:"jiji1234",
    foto:"png2",
    direccion:"Calle de la Desercción 2",
    telefono:443456789,
    tipo_usuario:"alumno",
    activo:true }
];

